spring:
  datasource:
    #基本属性
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# mybatis plus mapper 路径配置
## 如果使用 mybatis-plus-boot-starter 依赖，需要配置 mybatis-plus.mapper-locations
## 如果引用mybatis-plus 依赖，需要配置 mybatis.mapper-locations
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml