CREATE DATABASE `mybatis`CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `mybatis`;

CREATE TABLE IF NOT EXISTS  t_user(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL ,
  `password` VARCHAR(255) NOT NULL ,
  phone VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;