spring:
  application:
    name: rocketmq-produce

rocketmq:
  name-server: localhost:9876
  producer:
    group: sherlocky-group1
    sendMessageTimeout: 300000

# properties used in the application
sherlocky:
  rocketmq:
    topic: string-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    topic.user: user-topic
    bytesRequestTopic: bytesRequestTopic:tagA
    stringRequestTopic: stringRequestTopic:tagA
    objectRequestTopic: objectRequestTopic:tagA
    genericRequestTopic: genericRequestTopic:tagA
    extNameServer: 127.0.0.1:9876